-- MySQL Script generated by MySQL Workbench
-- 08/14/16 22:24:11
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema taskmanager
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `taskmanager` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `taskmanager` ;

-- -----------------------------------------------------
-- Table `taskmanager`.`task`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `taskmanager`.`task` ;

CREATE TABLE IF NOT EXISTS `taskmanager`.`task` (
  `idtask` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(200) NOT NULL,
  `status` VARCHAR(1) NOT NULL,
  `imgpath` VARCHAR(200) NULL,
  PRIMARY KEY (`idtask`),
  UNIQUE INDEX `idtask_UNIQUE` (`idtask` ASC))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
